### ISSUE TITLE
Not assets are installed when extra.component-dir is not defined.

### ISSUE THREAD

**Issue by m-vo** [contao-components/installer#7]
I ran into an issue, where I forgot to define `extra.component-dir` in my root `composer.json`. No assets will be installed in this case even though the readme states "By default, the components will be installed into a components/ directory". 

https://github.com/contao-components/installer/blob/eb0c34f0f61a3338dd985a55bd865483e78c3bb7/src/Composer/Plugin.php#L27-L31

I wondered if we could default to `assets` and remove the option at some point as this directory seems to be needed for Contao's other assets anyways like js/css/img (which are hardcoded). We would probably need to check if the current root `composer.json` is indeed an app, so that assets won't get installed when required during development of bundles.

**Comment by leofeyer** [comment]
The README is wrong. If there is no `extra.component-dir` (e.g. in the CI chain or in your local `contao/contao` clone), the assets shall not be installed.

**Comment by leofeyer** [comment]
Fixed in 9deb6450b00edfce7f2f8c83875584f984dc3a64.
